class UsernameTakenException(Exception):
    pass

class UserNotFoundException(Exception):
    pass